services:
  mysql:
    image: mysql:8.0
    container_name: mywiki-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "mywiki"
      MYSQL_USER: "mywiki"
      MYSQL_PASSWORD: "1234"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
