name: Deploy to Production Server

on:
  push:
    branches:
      - main

env:
  # Backend paths
  BACKEND_JAR_PATH: build/libs/
  REMOTE_BACKEND_PATH: "~/mywiki"
  
  # Frontend paths
  FRONTEND_SRC_PATH: ./frontend
  FRONTEND_BUILD_PATH: frontend/build
  REMOTE_FRONTEND_PATH: "/var/www/nginx"

jobs:
  deploy-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Backend Tests
        run: ./gradlew test

      - name: Build Backend JAR
        run: ./gradlew bootJar

      - name: Find JAR file name
        id: find_jar
        run: |
          JAR_FILE=$(find ${{ env.BACKEND_JAR_PATH }} -name "*.jar" | head -n 1)
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT

      - name: Create backend .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "OAUTH2_REDIRECT_URI=http://${{ secrets.SERVER_HOST }}" >> .env

      - name: Create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          script: mkdir -p ${{ env.REMOTE_BACKEND_PATH }}

      - name: SCP JAR file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          source: "${{ steps.find_jar.outputs.jar_file }}"
          target: "${{ env.REMOTE_BACKEND_PATH }}/app.jar"

      - name: SCP .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          source: ".env"
          target: "${{ env.REMOTE_BACKEND_PATH }}"

      - name: Execute remote deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            cd ${{ env.REMOTE_BACKEND_PATH }}
            echo "Stopping existing application..."
            pgrep -f app.jar | xargs -r kill -15
            sleep 5
            echo "Starting new application..."
            set -o allexport; source .env; set +o allexport
            nohup java -jar app.jar > app.log 2>&1 &

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js 18
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Create .env.production file
        working-directory: ${{ env.FRONTEND_SRC_PATH }}
        run: |
          echo "REACT_APP_API_BASE_URL=" > .env.production

      - name: Install and Build Frontend
        working-directory: ${{ env.FRONTEND_SRC_PATH }}
        run: |
          npm install
          npm run build

      - name: Prepare remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            sudo mkdir -p ${{ env.REMOTE_FRONTEND_PATH }}
            sudo chown -R ${{ secrets.SERVER_USERNAME }}:${{ secrets.SERVER_USERNAME }} ${{ env.REMOTE_FRONTEND_PATH }}
            rm -rf ${{ env.REMOTE_FRONTEND_PATH }}/*

      - name: SCP Frontend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          source: "${{ env.FRONTEND_BUILD_PATH }}/*"
          target: "${{ env.REMOTE_FRONTEND_PATH }}"
          strip_components: 2
